package Controllers;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

/**
 * Tests for ControllerOps class. Generated by ChatGPT, evaluated and adjusted by myself.
 *
 * @author Theodore Farias
 * @version 0.1.0
 * @since 8/11/2026
 */
class ControllerOpsTest {

  /**
   * Checks that a valid password entry provides the correct ControllerCode result.
   */
  @Test
  void checkPasswordValidPasswordReturnsSuccess() {
    String password = "Password1!";
    String confirmPassword = "Password1!";
    String[] fields = {"testUser", "Test Name", password, confirmPassword};

    ControllerCode result = ControllerOps.checkPassword(password, confirmPassword, fields);

    assertEquals(ControllerCode.SUCCESS, result);
  }

  /**
   * Check that the EMPTY_FIELD ControllerCode is returned when a field is left empty.
   */
  @Test
  void checkPasswordEmptyFieldReturnsEmptyField() {
    String password = "Password1!";
    String confirmPassword = "Password1!";
    String[] fields = {"testUser", "", password, confirmPassword};

    ControllerCode result = ControllerOps.checkPassword(password, confirmPassword, fields);

    assertEquals(ControllerCode.EMPTY_FIELD, result);
  }

  /**
   * Check that usernames that have spaces are not allowed. Returning the correct ControllerCode.
   */
  @Test
  void checkPasswordUsernameWithSpaceReturnsUsernameContainsSpace() {
    String password = "Password1!";
    String confirmPassword = "Password1!";
    String[] fields = {"test User", "Test Name", password, confirmPassword};

    ControllerCode result = ControllerOps.checkPassword(password, confirmPassword, fields);

    assertEquals(ControllerCode.USERNAME_CONTAINS_SPACE, result);
  }

  /**
   * Check that ControllerCode SHORT_PASSWORD is returned when password is obviously too short (< 8 characters)
   */
  @Test
  void checkPasswordTooShortReturnsShortPassword() {
    String password = "Pass1!";
    String confirmPassword = "Pass1!";
    String[] fields = {"testUser", "Test Name", password, confirmPassword};

    ControllerCode result = ControllerOps.checkPassword(password, confirmPassword, fields);

    assertEquals(ControllerCode.SHORT_PASSWORD, result);
  }

  /**
   * Check that entering different strings in password and confirmPassword fields provides the correct
   * ControllerCode.
   */
  @Test
  void checkPasswordDifferentPasswordsReturnsPasswordsDontMatch() {
    String password = "Password1!";
    String confirmPassword = "Different1!";
    String[] fields = {"testUser", "Test Name", password, confirmPassword};

    ControllerCode result = ControllerOps.checkPassword(password, confirmPassword, fields);

    assertEquals(ControllerCode.PASSWORDS_DONT_MATCH, result);
  }

  /**
   * Make sure that passwords that don't have the specified special characters
   * return a ControllerCode of NOT_REQUIRED_CHARS
   */
  @Test
  void checkPasswordMissingSpecialCharacterReturnsNotRequiredChars() {
    String password = "Password1";
    String confirmPassword = "Password1";
    String[] fields = {"testUser", "Test Name", password, confirmPassword};

    ControllerCode result = ControllerOps.checkPassword(password, confirmPassword, fields);

    assertEquals(ControllerCode.NOT_REQUIRED_CHARS, result);
  }

  /**
   * Make sure passwords that are at least 8 characters long are accepted.
   */
  @Test
  void checkPasswordLengthExactlyEightCharactersReturnsTrue() {
    // Edge case: 8 is the minimum accepted password length.
    String password = "Abcde1!x";

    assertTrue(ControllerOps.checkPasswordLength(password));
  }

  /**
   * Make sure that even a password that is only one character short will not be accepted.
   */
  @Test
  void checkPasswordLengthSevenCharactersReturnsFalse() {
    // Negative boundary case: one character below the minimum.
    String password = "Abcd1!x";

    assertFalse(ControllerOps.checkPasswordLength(password));
  }

  /**
   * Make sure that checkPasswordsMatch is returning true when they match.
   */
  @Test
  void checkPasswordsMatchMatchingPasswordsReturnsTrue() {
    assertTrue(ControllerOps.checkPasswordsMatch("Password1!", "Password1!"));
  }

  /**
   * Make sure that checkPasswordsMatch is returning false when they don't match.
   */
  @Test
  void checkPasswordsMatchDifferentPasswordsReturnsFalse() {
    assertFalse(ControllerOps.checkPasswordsMatch("Password1!", "PAssword1!"));
  }


  /**
   * Make sure a password with all requirements passes.
   */
  @Test
  void checkPasswordCharsValidPasswordReturnsTrue() {
    assertTrue(ControllerOps.checkPasswordChars("Password1!"));
  }

  /**
   * Make sure that a password without any uppercase letters fails.
   */
  @Test
  void checkPasswordCharsWithoutUppercaseReturnsFalse() {
    assertFalse(ControllerOps.checkPasswordChars("password1!"));
  }

  /**
   * Make sure that a password with no lowercase letters fails.
   */
  @Test
  void checkPasswordCharsWithoutLowercaseReturnsFalse() {
    assertFalse(ControllerOps.checkPasswordChars("PASSWORD1!"));
  }

  /**
   * Make sure that a password with no digits fails.
   */
  @Test
  void checkPasswordCharsWithoutNumberReturnsFalse() {
    assertFalse(ControllerOps.checkPasswordChars("Password!"));
  }

  /**
   * Make sure that a password with no special characters fails.
   */
  @Test
  void checkPasswordCharsWithoutSpecialCharacterReturnsFalse() {
    assertFalse(ControllerOps.checkPasswordChars("Password1"));
  }

  /**
   * Make sure that a password with a special character that is not specified fails.
   */
  @Test
  void checkPasswordCharsUnsupportedSpecialCharacterReturnsFalse() {
    // Edge case: '?' is punctuation, but it is not one of the accepted
    // special characters: ! @ # $ % ^ & *
    assertFalse(ControllerOps.checkPasswordChars("Password1?"));
  }
}